# Generated by Django 5.2.5 on 2025-10-13 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('backend', '0002_alter_budgetmodel_datetime'), ('backend', '0003_alter_budgetmodel_datetime'), ('backend', '0004_expensemodel_delete_budgetmodel'), ('backend', '0005_incomemodel'), ('backend', '0006_incomemodel_username'), ('backend', '0007_debtmodel'), ('backend', '0008_debtmodel_username'), ('backend', '0009_customuserprofile'), ('backend', '0010_alter_expensemodel_expense_rate'), ('backend', '0011_alter_debtmodel_debt_notes_and_more'), ('backend', '0012_alter_debtmodel_user'), ('backend', '0013_alter_debtmodel_debt_datetime'), ('backend', '0014_remove_debtmodel_debt_type_debtmodel_debt_rate_and_more'), ('backend', '0015_debtmodel_debt_interest_debtmodel_debt_payment'), ('backend', '0016_alter_debtmodel_debt_rate'), ('backend', '0017_alter_expensemodel_expense_rate_and_more'), ('backend', '0018_alter_debtmodel_username'), ('backend', '0019_alter_debtmodel_debt_amount_and_more'), ('backend', '0020_alter_debtmodel_debt_interest_and_more'), ('backend', '0021_alter_incomemodel_income_name_and_more'), ('backend', '0022_alter_expensemodel_managers'), ('backend', '0023_alter_expensemodel_managers'), ('backend', '0024_alter_expensemodel_expense_category')]

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('expense_name', models.CharField(blank=True, default='', max_length=100)),
                ('expense_category', models.CharField(blank=True, default='Essential', max_length=100)),
                ('expense_amount', models.FloatField(blank=True, default=0, max_length=10)),
                ('expense_notes', models.CharField(blank=True, default='', max_length=200)),
                ('expense_rate', models.CharField(blank=True, default='Weekly', max_length=20)),
                ('expense_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customUserModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BudgetModel',
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debt_amount', models.FloatField(blank=True, default=0.0)),
                ('debt_name', models.CharField(blank=True, default='')),
                ('debt_notes', models.CharField(blank=True, default='')),
                ('debt_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DebtModel', to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('debt_rate', models.CharField(blank=True, default='Weekly')),
                ('debt_interest', models.FloatField(blank=True, default=0)),
                ('debt_payment', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('income_amount', models.FloatField(default=0)),
                ('income_name', models.CharField(blank=True, default='')),
                ('income_type', models.CharField(blank=True, default='')),
                ('income_rate', models.CharField(blank=True, default='Weekly')),
                ('income_notes', models.CharField(blank=True, default='')),
                ('income_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserIncome', to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
